version: 2
jobs:
  test:
    working_directory: ~/service
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run linters
          command: make verify
      - run:
          name: Run unit tests
          command: make test-unit-coverage
      - run:
          name: Run integration tests
          command: make test-integration
workflows:
  version: 2
  test:
    jobs:
      - test
