name: Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 12 * * * # Runs at 12:00 UTC every day

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 10.x
    - run: npm ci
    - run: make build
    - run: make deploy
      env:
        FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY }}
    
  create-change-log:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Financial-Times/change-api-action@v1
        name: Create new change log
        with:
          change-api-key: ${{ secrets.CHANGE_API_KEY }}
          system-code: "origami-navigation-service-data"
          environment: prod
          slack-channels: "ft-changes,origami-deploys"
