name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 10.x
    - run: npm ci
    - run: make build
    - run: make verify
    - run: make test
