name: Deploy to production
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: sudo ~/project/.circleci/install_heroku.sh
      - run: ~/project/.circleci/create_netrc_file.sh
      - run: heroku pipelines:promote --app origami-navigation-service-qa --to origami-navigation-service-eu,origami-navigation-service-us