name: Deploy to production
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ~/project/.circleci/create_netrc_file.sh
    - run: git push https://git.heroku.com/origami-navigation-service-eu.git HEAD:master --force
    - run: git push https://git.heroku.com/origami-navigation-service-us.git HEAD:master --force
