name: Deploy to staging
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: ~/project/.circleci/create_netrc_file.sh
    - run: git push https://git.heroku.com/origami-navigation-service-qa.git HEAD:master --force